### ISSUE TITLE
Trouble iterating and building a data frame row by row

### ISSUE THREAD

**Issue by reuvenherzog** [VIS-2129-F2020/rherzog-vis#3]
My large goal for this chunk is to analyze how much green space is in every neighborhood of Tel Aviv.
Rough plan of how to accomplish this:
- for loop, iterate over every row in "neighborhoods"
- spatial subset "parks" by that neighborhood
- sum the area of parks in the subset
- create a row with neighborhood name, neighborhood number, and total_park_area
- add this new row to all the previous rows of neighborhood + park area
finally, when I have the full frame of all 71 neighborhoods with total park area, join this with the original neighborhoods table

When I run the code, everything works except the last step - I keep getting rows of data by neighborhood, but can't successfully aggregate them into a single data frame.
Please help!

Code is the final chunk of the rmd document in "Assignment 3"

**Comment by c-voulgaris** [comment]
In order for me to run your code, I need you do add the file "TLV neighborhoods with english.csv" to the directory on your computer that you're using as your repo. Once you do, you find that it appears in the Git tab of RStudio when you have your VIS project open, and you'll be able to commit that added file and push it to GitHub.

Once you've done that, change line 43 to 
```
  left_join(read_csv(file = "TLV neighborhoods with english.csv"), by = 'oid_shchuna')
```
You won't need to specify the full path if it's saved to your repo/working directory because that's where it looks by default.

And that will also make it so I can clone your repo to my local machine and I'll be able to run your code without having to modify it at all.

**Comment by reuvenherzog** [comment]
Done

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by c-voulgaris** [comment]
In general, although you can do loops in R, they're really slow, and there's often a faster, simpler solution that doesn't involve loops.

The trickiest thing about what you're trying to do is how to deal with parks that fall across neighborhood boundaries. From what I can tell, I think your parks dataset has includes 20 or so parks that overlap neighborhood boundaries. The method below (and the method you tried, I think) would count the entire area of these parks to both overlapping neighborhoods, so there'd be some double counting. If that's okay, then the code below should work:


```{r}
# remove duplicate parks
parks_unique <- st_difference(parks)

parks_nhood <- parks_unique %>%
  st_join(neighborhoods) %>%
  select(ms_area, oid_shchuna, eng_name)

st_geometry(parks_nhood) <- NULL

parks_nhood <- parks_nhood %>%
  group_by(eng_name) %>%
  summarise(park_area = sum(ms_area))

neighborhoods <- neighborhoods %>%
  left_join(parks_nhood) %>%
  mutate(park_area = ifelse(is.na(park_area), 0, park_area))

```
